# Project: Pertemuan3 - Lengan Bergerak
# Makefile created by Dev-C++ 5.7.1

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = mainLenganBergerak.o
LINKOBJ  = mainLenganBergerak.o
LIBS     = -L"C:/Windows/SysWOW64/Dev-Cpp/MinGW32/lib" -L"C:/Windows/SysWOW64/Dev-Cpp/MinGW32/mingw32/lib" -static-libstdc++ -static-libgcc -mwindows -lglut32 -lglu32 -lopengl32 -lwinmm -lgdi32
INCS     = -I"C:/Windows/SysWOW64/Dev-Cpp/MinGW32/include" -I"C:/Windows/SysWOW64/Dev-Cpp/MinGW32/mingw32/include" -I"C:/Windows/SysWOW64/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include"
CXXINCS  = -I"C:/Windows/SysWOW64/Dev-Cpp/MinGW32/include" -I"C:/Windows/SysWOW64/Dev-Cpp/MinGW32/mingw32/include" -I"C:/Windows/SysWOW64/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include" -I"C:/Windows/SysWOW64/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include/c++"
BIN      = "Pertemuan3 - Lengan Bergerak.exe"
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) -DGLUT_STATIC
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

mainLenganBergerak.o: mainLenganBergerak.cpp
	$(CPP) -c mainLenganBergerak.cpp -o mainLenganBergerak.o $(CXXFLAGS)
